import Generator from 'yeoman-generator'
import fs from 'fs-extra'
import _ from 'lodash'

const makeGeneratorName = name => {
  return _.kebabCase(name)
}

class ReactAppGenerator extends Generator {
  // Prompting Priority
  get prompting() {
    return {
      async askName() {
        const answers = await this.prompt([
          {
            type: 'input',
            name: 'name',
            message: 'Enter your project name:',
            filter: makeGeneratorName,
            default: 'sample-react-app',
          },
        ])
        const { name } = answers

        // Check if directory already exists
        const exists = await fs.pathExists(this.destinationPath(name))
        if (exists) {
          // Overwrite check
          const overwriteAnswers = await this.prompt([
            {
              type: 'confirm',
              name: 'overwrite',
              message: `A directory named '${name}' already exists. Would you like to overwrite?`,
            },
          ])
          if (overwriteAnswers.overwrite) {
            await fs.remove(this.destinationPath(name))
          } else {
            this.log('Exiting...')
            process.exit(0)
          }
        }

        this.name = name
        this.destinationRoot(this.destinationPath(name))
      },
    }
  }

  // Writing Priority
  get writing() {
    return {
      async writePackage() {
        const packageSettings = {
          name: this.name,
          private: true,
          version: '0.0.1',
          description: `${this.name} - Generated by @combine-labs/generator-react-app`,
          respository: '',
          author: 'Your name here',
        }
        await fs.writeJSON(
          this.destinationPath('package.json'),
          packageSettings
        )
      },

      async writePublicAssets() {
        await fs.copy(
          this.templatePath('index.html'),
          this.destinationPath('public/index.html')
        )
      },
    }
  }
}

export default ReactAppGenerator
