import Generator from 'yeoman-generator'
import chalk from 'chalk'
import fs from 'fs-extra'
import _ from 'lodash'
import { execSync } from 'child_process'

const makeGeneratorName = name => {
  return _.kebabCase(name)
}

const getGitStatus = () => {
  try {
    const stdout = execSync(`git status --porcelain`, {
      stdio: ['pipe', 'pipe', 'ignore'],
    }).toString()
    return stdout.trim()
  } catch (e) {
    return ''
  }
}

class ReactAppGenerator extends Generator {
  // Prompting Priority
  get prompting() {
    return {
      async askName() {
        const answers = await this.prompt([
          {
            type: 'input',
            name: 'name',
            message: 'Enter your project name:',
            filter: makeGeneratorName,
            default: 'sample-react-app',
          },
        ])
        const { name } = answers

        // Check if directory already exists
        const exists = await fs.pathExists(this.destinationPath(name))
        if (exists) {
          // Overwrite check
          const overwriteAnswers = await this.prompt([
            {
              type: 'confirm',
              name: 'overwrite',
              message: `A directory named '${name}' already exists. Would you like to overwrite?`,
            },
          ])
          if (overwriteAnswers.overwrite) {
            await fs.remove(this.destinationPath(name))
          } else {
            this.log(chalk.cyanBright('\nExiting...\n'))
            process.exit(0)
          }
        }
        this.name = name
      },
    }
  }

  // Configuring Priority
  get configuring() {
    return {
      // If there are untracked changes, Create React App eject will fail
      // Catch the error now before running create-react-app
      checkGitStatus() {
        const gitStatus = getGitStatus()
        if (gitStatus) {
          this.log(
            `${chalk.red('This git repository has untracked files or uncommitted changes:')}\n\n${gitStatus
              .split('\n')
              .map(line => line.match(/ .*/g)[0].trim())
              .join('\n')}\n\n${chalk.red('Remove untracked files, stash or commit any changes, and try again.')}`
          )
          process.exit(1)
        }
      },
    }
  }

  // Default Priority
  get default() {
    return {
      initWithCreateReactApp() {
        this.log(chalk.cyanBright('\nGenerating intial application using Create React App...\n'))
        this.spawnCommandSync('npx', ['create-react-app', this.name])
      },

      ejectCreateReactApp() {
        this.destinationRoot(this.destinationPath(this.name))
        this.log(chalk.cyanBright('\nEjecting Create React App\n'))
        const done = this.async() // spawnCommandSync doesn't like to pipe so use this strategy to handle async
        const yes = this.spawnCommand('echo', ['y'], {
          stdio: [process.stdin, 'pipe', process.stderr],
        })
        const eject = this.spawnCommand('yarn', ['eject'], { stdio: [yes.stdout, process.stdout, process.stderr] })
        eject.on('exit', code => {
          if (code !== 0) {
            this.env.error('Failed to eject Create React App')
          } else {
            this.log(chalk.cyanBright('\nCreate React App Ejected Successfully\n'))
          }
          done()
        })
      },
    }
  }

  // Writing Priority
  get writing() {
    return {
      // async writePackage() {
      //   this.log('WRITE PACKAGE')
      //   const packageSettings = {
      //     name: this.name,
      //     private: true,
      //     version: '0.0.1',
      //     description: `${this.name} - Generated by @combine-labs/generator-react-app`,
      //     respository: '',
      //     author: 'Your name here',
      //   }
      //   await fs.writeJSON(this.destinationPath('package.json'), packageSettings)
      // },

      async writeConfig() {
        await fs.copy(this.templatePath('template.editorconfig'), this.destinationPath('.editorconfig'))
      },

      // async writePublicAssets() {
      //   await fs.copy(this.templatePath('index.html'), this.destinationPath('public/index.html'))
      // },
    }
  }
}

export default ReactAppGenerator
